'use client';

import { useState } from 'react';
import { THEME } from '@/theme';

export default function SMSCenterPage() {
  const [smsTemplate, setSmsTemplate] = useState('DISBURSED');
  const [customSmsText, setCustomSmsText] = useState(
    'Dear {name}, your loan application has been approved and KES {amount} has been disbursed to your M-Pesa account. Thank you.'
  );
  const [smsLogs] = useState([
    { id: '1', recipient: 'Alice Wambui', time: '21:02:11', status: 'DELIVERED', content: 'Dear Alice, your loan of KES 50000 is approved...' },
    { id: '2', recipient: 'Karanja Ventures', time: '20:55:04', status: 'DELIVERED', content: 'Dear Karanja, your repayment of KES 12000 was received.' },
    { id: '3', recipient: 'David Kiprop', time: '20:00:22', status: 'QUEUED', content: 'Dear David, your payment of KES 25000 is due in 3 days.' },
  ]);

  return (
    <div className={THEME.classes.panel} style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div>
        <p className={THEME.classes.subtitle}>Automated Communications</p>
        <h2 className={THEME.classes.title} style={{ marginTop: 4 }}>SMS Notification Logs & Templates</h2>
        <p className={THEME.classes.textMuted} style={{ marginTop: 4, lineHeight: 1.6 }}>
          Manage automated texts generated by loan lifecycle events (Africa&apos;s Talking gateway integrations). Check queue delivery statuses.
        </p>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
        <div style={{ border: '1px solid #000', padding: '1.25rem', display: 'flex', flexDirection: 'column', gap: '1rem' }}>
          <h3 style={{ fontSize: '0.8125rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em' }}>Template Configuration</h3>
          
          <div>
            <label className={THEME.classes.textMuted} style={{ display: 'block', marginBottom: 6 }}>Trigger Event</label>
            <select
              value={smsTemplate}
              onChange={(e) => {
                setSmsTemplate(e.target.value);
                if (e.target.value === 'DISBURSED') {
                  setCustomSmsText('Dear {name}, your loan application has been approved and KES {amount} has been disbursed to your M-Pesa account. Thank you.');
                } else if (e.target.value === 'PAID') {
                  setCustomSmsText('Dear {name}, we have received your repayment of KES {amount}. Your new outstanding balance is KES {balance}.');
                } else {
                  setCustomSmsText('ALERT: Dear {name}, your loan is overdue by {days} days. Please pay KES {amount} immediately to avoid CRB blacklisting.');
                }
              }}
              className={THEME.classes.input}
            >
              <option value="DISBURSED">Loan Disbursement Confirmation</option>
              <option value="PAID">Repayment Receipt Notification</option>
              <option value="OVERDUE">Late Arrears Warning Alert</option>
            </select>
          </div>

          <div>
            <label className={THEME.classes.textMuted} style={{ display: 'block', marginBottom: 6 }}>SMS Body Text</label>
            <textarea
              value={customSmsText}
              onChange={(e) => setCustomSmsText(e.target.value)}
              className={THEME.classes.input}
              style={{ height: 96, resize: 'none' }}
            />
          </div>

          <button
            type="button"
            onClick={() => alert('SMS Template saved.')}
            className={THEME.classes.btnPrimary}
            style={{ width: '100%' }}
          >
            Save SMS Template
          </button>
        </div>

        <div style={{ border: '1px solid #000', padding: '1.25rem' }}>
          <h3 style={{ fontSize: '0.8125rem', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', marginBottom: '1rem' }}>Outbox Delivery Queue</h3>
          
          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
            {smsLogs.map((log) => (
              <div key={log.id} style={{ border: '1px solid #e4e4e7', padding: '0.75rem', fontSize: '0.6875rem' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontWeight: 700 }}>{log.recipient}</span>
                  <span style={{ color: '#71717a', fontSize: '0.625rem', fontFamily: 'monospace' }}>{log.time}</span>
                </div>
                <p style={{ color: '#71717a', marginTop: 4, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{log.content}</p>
                <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: 6 }}>
                  <span className={log.status === 'DELIVERED' ? THEME.classes.badgeFilled : THEME.classes.badgeMuted}>
                    {log.status}
                  </span>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}
