'use client';

import { useState } from 'react';

export default function SMSCenterPage() {
  const [smsTemplate, setSmsTemplate] = useState('DISBURSED');
  const [customSmsText, setCustomSmsText] = useState(
    'Dear {name}, your loan application has been approved and KES {amount} has been disbursed to your M-Pesa account. Thank you.'
  );
  const [smsLogs, setSmsLogs] = useState([
    { id: '1', recipient: 'Alice Wambui', time: '21:02:11', status: 'DELIVERED', content: 'Dear Alice, your loan of KES 50000 is approved...' },
    { id: '2', recipient: 'Karanja Ventures', time: '20:55:04', status: 'DELIVERED', content: 'Dear Karanja, your repayment of KES 12000 was received.' },
    { id: '3', recipient: 'David Kiprop', time: '20:00:22', status: 'QUEUED', content: 'Dear David, your payment of KES 25000 is due in 3 days.' },
  ]);

  return (
    <div className="glass-panel rounded-[28px] p-6 space-y-6">
      <div>
        <p className="text-[10px] font-bold uppercase tracking-[0.2em] text-amber-500">Automated Communications</p>
        <h2 className="text-xl font-bold tracking-tight text-white mt-1">SMS Notification logs & Templates</h2>
        <p className="text-xs text-slate-500 mt-1 leading-relaxed">
          Manage automated texts generated by loan lifecycle events (Africa's Talking gateway integrations). Check queue delivery statuses.
        </p>
      </div>

      <div className="grid gap-6 md:grid-cols-2">
        <div className="space-y-5 rounded-2xl border border-white/5 bg-white/[0.02] p-5">
          <h3 className="text-sm font-semibold text-white">Template Configuration</h3>
          
          <div>
            <label className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">Trigger Event</label>
            <select
              value={smsTemplate}
              onChange={(e) => {
                setSmsTemplate(e.target.value);
                if (e.target.value === 'DISBURSED') {
                  setCustomSmsText('Dear {name}, your loan application has been approved and KES {amount} has been disbursed to your M-Pesa account. Thank you.');
                } else if (e.target.value === 'PAID') {
                  setCustomSmsText('Dear {name}, we have received your repayment of KES {amount}. Your new outstanding balance is KES {balance}.');
                } else {
                  setCustomSmsText('ALERT: Dear {name}, your loan is overdue by {days} days. Please pay KES {amount} immediately to avoid CRB blacklisting.');
                }
              }}
              className="premium-select w-full rounded-xl px-4 py-3 text-sm outline-none"
            >
              <option value="DISBURSED">Loan Disbursement Confirmation</option>
              <option value="PAID">Repayment Receipt Notification</option>
              <option value="OVERDUE">Late Arrears Warning Alert</option>
            </select>
          </div>

          <div>
            <label className="mb-1.5 block text-[10px] font-bold uppercase tracking-wider text-slate-400">SMS Body Text</label>
            <textarea
              value={customSmsText}
              onChange={(e) => setCustomSmsText(e.target.value)}
              className="premium-input w-full rounded-xl px-4 py-3 text-sm outline-none h-24 resize-none"
            />
          </div>

          <button
            type="button"
            onClick={() => alert('SMS Template saved.')}
            className="w-full rounded-xl bg-gradient-to-r from-amber-500 to-desert-500 hover:from-amber-600 hover:to-desert-600 py-2.5 text-xs font-bold text-white shadow-md transition-all duration-200"
          >
            Save SMS Template
          </button>
        </div>

        <div className="rounded-2xl border border-white/5 bg-white/[0.02] p-5">
          <h3 className="text-sm font-semibold text-white mb-4">Outbox Delivery Queue</h3>
          
          <div className="space-y-3">
            {smsLogs.map((log) => {
              const badge = log.status === 'DELIVERED' 
                ? 'bg-emerald-500/10 text-emerald-400 border-emerald-500/20' 
                : 'bg-amber-500/10 text-amber-400 border-amber-500/20';
              return (
                <div key={log.id} className="rounded-xl border border-white/5 bg-black/20 p-3 text-[11px] space-y-1.5">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold text-slate-200">{log.recipient}</span>
                    <span className="text-[10px] text-slate-500">{log.time}</span>
                  </div>
                  <p className="text-slate-400 line-clamp-1">{log.content}</p>
                  <div className="flex justify-end">
                    <span className={`rounded-full border px-2 py-0.5 text-[8px] font-semibold ${badge}`}>
                      {log.status}
                    </span>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </div>
  );
}
